# Send prefix
set-option -g prefix C-a
unbind-key C-a
bind-key C-a send-prefix

# Use Alt-arrow keys to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left previous-window
bind -n S-Right next-window

set -g set-clipboard on
set -g base-index 1
set -g renumber-windows on
setw -g mouse on
set -g status-position bottom 
set -g base-index 1

# Set easier window split keys
bind-key v split-window -hc "#{pane_current_path}"
bind-key h split-window -vc "#{pane_current_path}"

bind c new-window -c "#{pane_current_path}"

# Set 256 colors
set -g default-terminal "screen-256color"

# Easy config reload
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded."

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'dracula/tmux'

set -g @dracula-show-powerline true
set -g @dracula-plugins "time"
# set -g @dracula-fixed-location "Havana"
set -g @dracula-show-fahrenheit false
set -g @dracula-show-location false
set -g @dracula-show-timezone false
set -g @dracula-day-month true
set -g @dracula-military-time true
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
